const concepts=[
['01-fieldnotes','Fieldnotes','Editorial / CSS','A civic journal with oversized type and deliberate margins.','Read the margins, then switch the annotation view.'],
['02-ledger','Ledger','Layers / CSS 3D','Evidence becomes a stack you can inspect.','Select an evidence layer and change its depth.'],
['03-assembly','Assembly','Three.js / WebGL','A mark made of parts, brought together by you.','Move your pointer and pull the assembled mark apart.'],
['04-signal','Signal','Three.js / WebGL','Cobalt, scale, and a field that responds.','Explore the field and switch its focus.'],
['05-material','Material','Blender / alpha','A small sculpture with an unmistakable presence.','Move your pointer to feel the type and object separate.'],
['06-aperture','Aperture','ImageGen / CSS','Transparency, made tangible through light.','Inspect the glass button: a small echo of the object.']
];
const cards=document.querySelector('#cards'),chooser=document.querySelector('#chooser'),overview=document.querySelector('#overview'),viewer=document.querySelector('#viewer'),frame=document.querySelector('#concept-frame'),overviewButton=document.querySelector('#overview-button');
for(const [i,c] of concepts.entries()){const card=document.createElement('button');card.className='card';card.setAttribute('aria-label',`Explore ${c[1]}: ${c[3]}`);card.innerHTML=`<div class="card-visual"><img src="assets/previews/${c[0]}.jpg" alt="${c[1]} desktop concept preview" loading="lazy"><span class="play" aria-hidden="true">↗</span></div><div class="card-meta"><span class="card-title"><span class="number">0${i+1}</span>${c[1]}</span><span class="card-tech">${c[2]}</span></div><p>${c[3]}</p>`;card.addEventListener('click',()=>show(i));cards.append(card);const button=document.createElement('button');button.textContent=`0${i+1}`;button.setAttribute('aria-label',`Show ${c[1]}`);button.setAttribute('aria-pressed','false');button.addEventListener('click',()=>show(i));chooser.append(button)}
let activeConcept=-1;
function show(index,moveFocus=true){activeConcept=index;const c=concepts[index];overview.hidden=true;viewer.hidden=false;overviewButton.setAttribute('aria-pressed','false');frame.src=`concepts/${c[0]}/`;frame.title=`OpenPali — ${c[1]} interactive concept`;document.querySelector('#standalone').href=frame.src;document.querySelector('#concept-title').textContent=`0${index+1} / ${c[1]}`;document.querySelector('#concept-note').textContent=c[4];document.querySelector('#concept-tech').textContent=c[2];[...chooser.children].forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));history.replaceState(null,'',`#${c[0]}`);if(moveFocus)chooser.children[index].focus({preventScroll:true})}
function showOverview(){overview.hidden=false;viewer.hidden=true;frame.removeAttribute('src');overviewButton.setAttribute('aria-pressed','true');history.replaceState(null,'','#overview');if(activeConcept>=0)cards.children[activeConcept].focus({preventScroll:true})}
overviewButton.addEventListener('click',showOverview);document.querySelector('.identity').addEventListener('click',showOverview);
for(const button of document.querySelectorAll('[data-device]'))if(button.tagName==='BUTTON')button.addEventListener('click',()=>{document.querySelector('.frame-area').dataset.device=button.dataset.device;for(const b of document.querySelectorAll('.viewport-options button'))b.setAttribute('aria-pressed',String(b===button))});
const initial=concepts.findIndex(c=>location.hash===`#${c[0]}`);if(initial>=0)show(initial,false);
